---
# Example of all namespaces definition
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: artifacts
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab-stands
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
