---
# Cilium CNI Installation Configuration

# Install Cilium using Helm

apiVersion: v1
kind: Namespace
metadata:
  name: cilium
  labels:
    name: cilium
---
# Cilium ConfigMap for configuration
# Cilium ConfigMap for configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: cilium
data:
  # Enable IPv4
  # Enable IPv4
  enable-ipv4: "true"
  # Enable IPv6 (optional)
  # Enable IPv6 (optional)
  enable-ipv6: "false"
  # Enable kube-proxy replacement
  # Enable kube-proxy replacement
  enable-kube-proxy-replacement: "true"
  # Enable BPF masquerade
  # Enable BPF masquerade
  enable-bpf-masquerade: "true"
  # Enable host reachable services
  # Enable host reachable services
  enable-host-reachable-services: "true"
  # Enable external IPs
  # Enable external IPs
  enable-external-ips: "true"
  # Enable NodePort
  # Enable NodePort
  enable-node-port: "true"
  # Enable host port
  # Enable host port
  enable-host-port: "true"
  # Enable session affinity
  # Enable session affinity
  enable-session-affinity: "true"
  # Enable Bandwidth Manager
  # Enable Bandwidth Manager
  enable-bandwidth-manager: "true"
  # Enable Local Redirect Policy
  # Enable Local Redirect Policy
  enable-local-redirect-policy: "true"
  # Enable Hubble
  # Enable Hubble
  enable-hubble: "true"
  # Hubble metrics server
  # Hubble metrics server
  hubble-metrics-server: "true"
  # Hubble relay
  # Hubble relay
  hubble-relay: "true"
  # Hubble UI
  # UI Hubble
  hubble-ui: "true"
  # Enable Prometheus metrics
  # Enable Prometheus metrics
  enable-prometheus-metrics: "true"
  # Monitor aggregation
  # Monitor aggregation
  monitor-aggregation: "medium"
  # Preallocate BPF maps
  # Preallocate BPF maps
  preallocate-bpf-maps: "true"
  # Enable auto direct routing
  # Enable auto direct routing
  enable-auto-direct-routing: "true"
  # Enable endpoint routes
  # Enable endpoint routes
  enable-endpoint-routes: "true"
  # Enable policy
  # Enable policy
  enable-policy: "true"
  # Enable L7 proxy
  # Enable L7 proxy
  enable-l7-proxy: "true"
  # Enable BPF clock probe
  # Enable BPF clock probe
  enable-bpf-clock-probe: "true"
  # Enable well known identities
  # Enable well known identities
  enable-well-known-identities: "true"
  # Enable remote node identity
  # Enable remote node identity
  enable-remote-node-identity: "true"
  # Enable health checking
  enable-health-checking: "true"
  # Enable health checking nodeport
  enable-health-checking-nodeport: "true"
  # Enable health checking loadbalancer ip
  enable-health-checking-loadbalancer-ip: "true"
  # Enable health checking with HTTP
  enable-health-checking-http: "true"
  # Enable health checking with HTTP path
  enable-health-checking-http-path: "/healthz"
  # Enable health checking with HTTP method
  enable-health-checking-http-method: "GET"
  # Enable health checking with HTTP expected status
  enable-health-checking-http-expected-status: "200"
  # Enable health checking with HTTP timeout
  enable-health-checking-http-timeout: "5s"
  # Enable health checking with HTTP retries
  enable-health-checking-http-retries: "3"
  # Enable health checking with HTTP interval
  enable-health-checking-http-interval: "30s"
  # Enable health checking with HTTP grace period
  enable-health-checking-http-grace-period: "5s"
  # Enable health checking with HTTP failure threshold
  enable-health-checking-http-failure-threshold: "3"
  # Enable health checking with HTTP success threshold
  enable-health-checking-http-success-threshold: "1"
  # Enable health checking with HTTP initial delay
  enable-health-checking-http-initial-delay: "30s"
  # Enable health checking with HTTP period
  enable-health-checking-http-period: "10s"
  # Enable health checking with HTTP timeout seconds
  enable-health-checking-http-timeout-seconds: "5"
  # Enable health checking with HTTP initial delay seconds
  enable-health-checking-http-initial-delay-seconds: "30"
  # Enable health checking with HTTP period seconds
  enable-health-checking-http-period-seconds: "10"
  # Enable health checking with HTTP liveness probe
  enable-health-checking-http-liveness-probe: "true"
  # Enable health checking with HTTP readiness probe
  enable-health-checking-http-readiness-probe: "true"
  # Enable health checking with HTTP startup probe
  enable-health-checking-http-startup-probe: "true"
  # Enable health checking with HTTP exec probe
  enable-health-checking-http-exec-probe: "true"
  # Enable health checking with HTTP tcp socket probe
  enable-health-checking-http-tcp-socket-probe: "true"
  # Enable health checking with HTTP grpc probe
  enable-health-checking-http-grpc-probe: "true"
  # Enable health checking with HTTP http get probe
  enable-health-checking-http-http-get-probe: "true"
  # Enable health checking with HTTP http post probe
  enable-health-checking-http-http-post-probe: "true"
  # Enable health checking with HTTP http put probe
  enable-health-checking-http-http-put-probe: "true"
  # Enable health checking with HTTP http delete probe
  enable-health-checking-http-http-delete-probe: "true"
  # Enable health checking with HTTP http patch probe
  enable-health-checking-http-http-patch-probe: "true"
  # Enable health checking with HTTP http head probe
  enable-health-checking-http-http-head-probe: "true"
  # Enable health checking with HTTP http options probe
  enable-health-checking-http-http-options-probe: "true"
  # Enable health checking with HTTP http trace probe
  enable-health-checking-http-http-trace-probe: "true"
  # Enable health checking with HTTP http connect probe
  enable-health-checking-http-http-connect-probe: "true"
