apiVersion: v1
kind: Namespace
metadata:
  name: gitops
  labels:
    name: gitops
    app: argocd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: gitops
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-server
  namespace: gitops
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: gitops
  labels:
    app: argocd
    component: server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: argocd
    component: server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: gitops
  labels:
    app: argocd
    component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
      component: server
  template:
    metadata:
      labels:
        app: argocd
        component: server
    spec:
      nodeSelector:
        node-type: big
      serviceAccountName: argocd-server
      containers:
      - name: argocd-server
        image: quay.io/argoproj/argocd:v2.8.4
        command:
        - argocd-server
        - --staticassets
        - /shared/app
        - --insecure
        - --disable-auth
        ports:
        - containerPort: 8080
        - containerPort: 8083
        env:
        - name: ARGOCD_API_SERVER_REPLICAS
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: static-files
          mountPath: /shared/app
      volumes:
      - name: static-files
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-application-controller
  namespace: gitops
  labels:
    app: argocd
    component: application-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
      component: application-controller
  template:
    metadata:
      labels:
        app: argocd
        component: application-controller
    spec:
      nodeSelector:
        node-type: big
      serviceAccountName: argocd-application-controller
      containers:
      - name: argocd-application-controller
        image: quay.io/argoproj/argocd:v2.8.4
        command:
        - argocd-application-controller
        env:
        - name: ARGOCD_RECONCILIATION_TIMEOUT
          value: "180s"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: gitops
  labels:
    app: argocd
    component: configmap
data:
  url: http://argocd.gitops.svc.cluster.local
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  configManagementPlugins: |
    - name: kustomize
      init:
        command: [sh, -c]
        args: ["echo 'Initializing kustomize'"]
      generate:
        command: [kustomize, build]
        args: [.]
    - name: helm
      init:
        command: [sh, -c]
        args: ["echo 'Initializing helm'"]
      generate:
        command: [helm, template]
        args: [.]
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: gitops
  labels:
    app: argocd
    component: secret
type: Opaque
data:
  admin.password: YWRtaW4=  # admin
  admin.passwordMtime: MjAyNC0wMS0wMVQwMDowMDowMFo= 